apiVersion: v1
kind: ConfigMap
metadata:
  name: site-nginx-config
data:
  default.conf: |
    server {
      listen 80 default_server;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location = /webpages {
        try_files /webpages/index.html =404;
      }

      location = /webpages/ {
        try_files $uri $uri/ /webpages/index.html;
      }

      location / {
        try_files $uri $uri/ /webpages/index.html;
      }
    }
