apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-oci

resources:
  - namespace.yaml
  - certificate.yaml
  - oci-test-deployment.yaml
  - oci-test-service.yaml
  - oci-test-ingress.yaml
  - oci-test-nginx-config.yaml
  - webpages-deployment.yaml
  - webpages-service.yaml
  - webpages-ingress.yaml
  - webpages-nginx-config.yaml
