apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpages
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-live
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: k8s-oci-redirect-to-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rghf.nl
        - www.rghf.nl
      secretName: web-tls
  rules:
    - host: rghf.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webpages
                port:
                  number: 80
    - host: www.rghf.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webpages
                port:
                  number: 80
